### ISSUE TITLE
update values

### ISSUE THREAD

**Issue by jgpATs2w** [phetsims/babel#12]
Hi, I've created a fork and I'm checking the 'es' locale. In order to do it properly to make changes acceptable in pull request, I need to know if there is any app to translate and generate the history array entries, or by updating the value property to the right one is enough.

**Comment by jbphet** [comment]
Greetings Javier, and thanks for your interest in translating PhET simulations.  The translations are actually generated through a web interface, which is much easier than creating forks and submitting pull requests.  If you're interested in creating translations, please email phethelp@colorado.edu.  Also, you can see more information about the translation process at https://phet.colorado.edu/en/for-translators.

**Comment by jbphet** [comment]
Closing, since @jgpATs2w should now have the information needed to create a translation if desired.
