### ISSUE TITLE
Delete auto-ported strings, update checklist to reflect new process

### ISSUE THREAD

**Issue by jbphet** [phetsims/babel#15]
In the 1/31/2019 developer meeting, we decided to stop moving over the auto-ported strings from the Java and Flash sims into ported HTML5 sims.  The main reason is that the build process has changed, and it will cause translations to be built from auto-ported strings on the first deployment of the sim, which is generally undesirable since there are pretty much always changes to the strings from the Java version, which makes the translation incomplete.  This happened when Energy Forms and Changes was first deployed in late January 2019.

The "autoported" directory should be deleted and the step about converting the strings should be removed from the master checklist document.

**Comment by jbphet** [comment]
@ariel-phet - you mentioned that I should assign this to you, but I went ahead and updated the document while also deleting the old auto-ported strings since it was quick.  Please check my changes and, if it looks okay (and if there aren't any other docs that need to be updated), I think this can be closed.

**Comment by ariel-phet** [comment]
Looks good, closing
