### ISSUE TITLE
Delete sound-waves-1.0 branch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/babel#23]
Slack#developer thread:

@pixelzoom 
Why does babel have a “sound-waves-1.0” branch?  Aren’t strings always taken from main?
Looks like that branch was created by @matthew-blackman around 9/8/2023.

@matthew-blackman 
It looks like that was created in error while cherry-picking updated strings for Sound Waves. Okay if I just remove the branch?

@pixelzoom 
I think removing the branch is the right thing to do. But verify with @jbphet.
And you might need to work around branch protection rules to delete the branch.

@matthew-blackman 
Thanks! I will reach out to @jbphet for next steps.

**Comment by matthew-blackman** [comment]
I spoke with @jbphet and we weren't aware of any branch protection rules. The sound-waves-1.0 branch has been removed from babel. @pixelzoom can you confirm and close if all looks good?

**Comment by pixelzoom** [comment]
I still see the sound-waves-1.0 branch in GitHub: https://github.com/phetsims/babel/tree/sound-waves-1.0

And after a pull-all, I still see the sound-waves-1.0 branch via the git command line:

> % git branch -r
  origin/HEAD -> origin/main
  origin/main
  origin/master
  origin/sound-waves-1.0
  origin/tests

**Comment by matthew-blackman** [comment]
My apologies, I've re-deleted the sound-waves-1.0 branch from GitHub and remote. There did end up being a branch rule to get around. Can you verify it's gone on your end?

**Comment by pixelzoom** [comment]
👍🏻 Closing.
