### ISSUE TITLE
bogus files, probably due to testing

### ISSUE THREAD

**Issue by jbphet** [phetsims/babel#5]
The joist directory of this repo has two files that don't look correct, and are probably there as a result of some of the recent testing.  These should be deleted.  This was discussed in the 8/25/2015 dev meeting.

**Comment by pixelzoom** [comment]
Which 2 files?

**Comment by jbphet** [comment]
The files were joist-strings_es.json and joist-strings_nb.json, and were the only two string files in joist.  They have been deleted.  Closing.
