### ISSUE TITLE
Convention for string keys?

### ISSUE THREAD

**Issue by samreid** [phetsims/babel#8]
I am inclined to use this style from Hooke's Law:

``` js
  "appliedForceNumber": {
    "value": "Applied Force {0}:"
  },
```

instead of this style from Hooke's Law:

``` js
  "pattern.0value.1units": {
    "value": "{0} {1}"
  },
```

@pixelzoom @jessegreenberg @jbphet @jonathanolson any thoughts?

**Comment by pixelzoom** [comment]
I don't care which convention we choose, or even if we choose one.

If we do decide to standardize, we'll also need to decided whether to change existing keys, which would be a huge hassle.

**Comment by jbphet** [comment]
I see the examples above as two different things.  One is a combination of text and a value, the other is only a pattern that specifies the order.  I've been using both, each for the context to which it applies.

**Comment by pixelzoom** [comment]
@jbphet Good point in https://github.com/phetsims/babel/issues/8#issuecomment-192357925.

I've heard @jonathanolson argue that patterns like `"pattern.0value.1units"` are too general, and that we should have a different pattern for  (in this case) every each different unit.  Not sure I agree with that in all cases.  But that's probably another aspect where "standardization" might be in order. Anyone else have an opinion?

**Comment by pixelzoom** [comment]
Now that we've deprecated patterns with numbered placeholders, and switched to patterns with _named_ placeholders (see https://github.com/phetsims/phetcommon/issues/36), the discussion about keys containing numbers (e.g. "pattern.0value.1units") seems to be moot.  We're not going to change these keys in existing translations, and we're not going to create more of these keys going forward. 

So.... What should the convention be for patterns with _named_ placeholders?  

How about something like this? :

```js
"valueUnits": {
    "value": "{value} {units}"
  },
"myNameIsFirstNameLastName": {
    "value": "My name is {firstName} {lastName}."
  },
```

**Comment by pixelzoom** [comment]
Labeling for developer meeting.  Since named placeholders are not widely used yet, deciding on a convention for this likely "now or never".

**Comment by samreid** [comment]
Proposal in https://github.com/phetsims/babel/issues/8#issuecomment-297599044 seems great.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/babel/issues/8#issuecomment-297599044 👍  that seems great to me.

**Comment by jonathanolson** [comment]
Sounds like a nice convention. As an example, what would the name for a string with just `"{{price}}"` be? (Current proportion-playground string key is `pricePattern`).

**Comment by samreid** [comment]
Just to clarify, the string file for Proportion playground has

```json
  "pricePattern": {
    "value": "${{price}}"
  },
```

Would "price" be a reasonable key?

**Comment by jonathanolson** [comment]
> Would "price" be a reasonable key?

Seems likely to conflict with a string (that doesn't exist in this particular case, but in general could) whose text is `"Price"`.

**Comment by samreid** [comment]
Good point! Sounds like it should not be `price`!

**Comment by pixelzoom** [comment]
Perhaps we should have a common prefix or suffix on all strings that contain placeholders?

**Comment by pixelzoom** [comment]
Perhaps we should have a common prefix or suffix on all strings that contain placeholders?

E.g., the examples above would become:

> valueUnitsPattern
myNameIsFirstNameLastNamePattern
pricePattern

or 

> patternValueUnits
patternMyNameIsFirstNameLastName
patternPrice

**Comment by samreid** [comment]
@jessegreenberg and @jonathanolson and @samreid voted for suffix.  @jonathanolson pointed out that sometimes we may need to work outside of this convention.

@Denz1994 and @ariel-phet chimed in voting for the suffix.

**Comment by pixelzoom** [comment]
We'll go with "Patterns" suffix.  I'll determine what documentation needs to be updated.  Definitely in code-review checklist, maybe in Code Style Guidelines.

**Comment by pixelzoom** [comment]
"{{dollars}} dollars and {{cents}} cents" blows up our convention.  "dollarsDollarsCenterCentsPattern" is UG-ly.  

We decided instead that the convention should be "pick good keys that aren't likely to conflict with other keys".  I'll review the docs to see if anything needs to change.

**Comment by pixelzoom** [comment]
Code-review checklist updated in above commit.

There is nothing related to patterns in the PhET Development Overview.

Closing.
